# 🥅 sentry-webhook: Dead simple webhook worker for Sentry to output events in a Discord channel
# Copyright 2022 Noel <cutie@floofy.dev>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name    = "sentry-worker"
version = "0.1.2"
edition = "2021"
authors = ["Noel <cutie@floofy.dev>"]

[dependencies]
fern = "0.6.1"
tokio = { version = "1.18.2", features = ["full"] }
log = "0.4.17"
serde = "1.0.137"
toml = "0.5.9"
once_cell = "1.11.0"
sentry = "0.25.0"
reqwest = { version = "0.11", features = ["json"] }
ansi_term = "*"
chrono = "*"
warp = "0.3.2"
sha256 = "*"
serde_json = "*"

[[bin]]
path = "src/main.rs"
name = "sentry_webhook"
